apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projet-devops-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: projet-devops-pv