apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      volumes:
        - name: my-vol
          persistentVolumeClaim:
            claimName: projet-devops-pv-claim
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: my-vol
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-deployment
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379