apiVersion: v1

kind: Service
metadata:
  name: projet-devops-service
spec:
  selector:
    app: projet-devops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
